// GENERATED by scripts/generate-legal-hash.mjs — do not edit by hand.
// Regenerated before every build; commit the result so type-checking works
// without running the script first.
export const LEGAL_CONTENT_HASH = '9c802091652c3bb98c5ccb9bcd4c09951931cd17f056bd1ced250861b7c59b0a';
