// GENERATED by scripts/generate-legal-hash.mjs — do not edit by hand.
// Regenerated before every build; commit the result so type-checking works
// without running the script first.
export const LEGAL_CONTENT_HASH = '46f6b0b7593c9a3b1c6d57d66372df19f47ab32a3520bfb4549d6605b4c3d79a';
