// GENERATED by scripts/generate-legal-hash.mjs — do not edit by hand.
// Regenerated before every build; commit the result so type-checking works
// without running the script first.
export const LEGAL_CONTENT_HASH = '6e876c6b7dd3ebfac12b30bc0f192f21b741eae8c97ae44e9ec3760b457c6bb0';
