import { createHash } from 'node:crypto';
import { and, asc, eq } from 'drizzle-orm';
import { db } from '@/lib/db/drizzle';
import { sessionAudioRecordings, sessionTranscriptSegments, sessionTranscriptTimelineSegments } from '@/lib/db/schema';

export type TimelineSource = { id: number; participantRecordingId: number; participantUserId: number | null; participantRole: 'coach' | 'athlete'; participantSequence: number; startMs: number; endMs: number; text: string; provider: string | null; model: string | null };
export type TimelineSegment = TimelineSource & { globalSequence: number; normalizedText: string; flags: Record<string, boolean> };
export function normalizeTranscriptText(value: string): string { return value.replace(/\r\n?/g, '\n').replace(/[\u2018\u2019]/g, "'").replace(/[\u201C\u201D]/g, '"').replace(/[\u2013\u2014]/g, '-').replace(/\s+/g, ' ').trim(); }
export function sourceFingerprint(sources: TimelineSource[]): string { return createHash('sha256').update(sources.slice().sort((a,b) => a.id-b.id).map(s => [s.id,s.participantSequence,s.startMs,s.endMs,s.text,s.provider,s.model].join('|')).join('\n')).digest('hex'); }
export function buildTimeline(sources: TimelineSource[]): { segments: TimelineSegment[]; statistics: Record<string, number>; fingerprint: string } {
  const valid = sources.flatMap(source => { const normalizedText = normalizeTranscriptText(source.text); if (!normalizedText || source.endMs < source.startMs || source.startMs < 0) return []; const flags: Record<string, boolean> = {}; if (source.endMs === source.startMs) flags.duration_zero = true; return [{...source, normalizedText, flags}]; });
  valid.sort((a,b) => a.startMs-b.startMs || a.endMs-b.endMs || a.participantRole.localeCompare(b.participantRole) || a.id-b.id);
  let previousEnd=0, overlap=0, gaps=0; const durations={coach:0,athlete:0}; const counts={coach:0,athlete:0};
  const segments = valid.map((source,globalSequence) => { if(globalSequence && source.startMs<previousEnd) { source.flags.overlaps_previous=true; overlap += Math.min(previousEnd,source.endMs)-source.startMs; } if(globalSequence && source.startMs-previousEnd>=5000) {source.flags.large_gap_before=true; gaps += source.startMs-previousEnd;} previousEnd=Math.max(previousEnd,source.endMs); durations[source.participantRole]+=source.endMs-source.startMs; counts[source.participantRole]++; return {...source,globalSequence}; });
  const total=durations.coach+durations.athlete;
  return {segments,fingerprint:sourceFingerprint(sources),statistics:{total_timeline_duration_ms:segments.length?previousEnd-segments[0].startMs:0,coach_speaking_duration_ms:durations.coach,athlete_speaking_duration_ms:durations.athlete,coach_segment_count:counts.coach,athlete_segment_count:counts.athlete,coach_percentage:total?durations.coach/total:0,athlete_percentage:total?durations.athlete/total:0,silence_gap_duration_ms:gaps,overlap_duration_ms:overlap,first_timestamp_ms:segments[0]?.startMs??0,last_timestamp_ms:segments.at(-1)?.endMs??0,source_segment_count:sources.length,normalized_segment_count:segments.length}};
}

/** Rebuilds the derived private projection; source segments are never changed. */
export async function rebuildSessionTimeline(sessionId: number, actorUserId: number) {
  const rows = await db.select({ id: sessionTranscriptSegments.id, participantRecordingId: sessionTranscriptSegments.participantRecordingId, participantUserId: sessionTranscriptSegments.participantUserId, participantRole: sessionTranscriptSegments.speakerRole, participantSequence: sessionTranscriptSegments.sequenceNumber, localStart: sessionTranscriptSegments.startedAtMs, localEnd: sessionTranscriptSegments.endedAtMs, text: sessionTranscriptSegments.text, provider: sessionTranscriptSegments.provider, model: sessionTranscriptSegments.providerModel, physicalId: sessionTranscriptSegments.physicalRecordingId, physicalStartedAt: sessionAudioRecordings.startedAt }).from(sessionTranscriptSegments).innerJoin(sessionAudioRecordings, eq(sessionAudioRecordings.id, sessionTranscriptSegments.physicalRecordingId)).where(eq(sessionTranscriptSegments.sessionAiNotesId, sessionId)).orderBy(asc(sessionAudioRecordings.segmentOrder), asc(sessionTranscriptSegments.sequenceNumber));
  if (rows.some(r => !r.participantRecordingId || !r.physicalStartedAt || r.participantRole !== 'coach' && r.participantRole !== 'athlete')) throw new Error('TIMELINE_OFFSETS_UNAVAILABLE');
  const base = Math.min(...rows.map(r => r.physicalStartedAt!.getTime()));
  const timeline = buildTimeline(rows.map(r => ({ id:r.id, participantRecordingId:r.participantRecordingId!, participantUserId:r.participantUserId, participantRole:r.participantRole as 'coach'|'athlete', participantSequence:r.participantSequence, startMs:r.physicalStartedAt!.getTime()-base+r.localStart, endMs:r.physicalStartedAt!.getTime()-base+r.localEnd, text:r.text, provider:r.provider, model:r.model })));
  await db.transaction(async tx => { await tx.delete(sessionTranscriptTimelineSegments).where(eq(sessionTranscriptTimelineSegments.sessionAiNotesId,sessionId)); if(timeline.segments.length) await tx.insert(sessionTranscriptTimelineSegments).values(timeline.segments.map(s => ({sessionAiNotesId:sessionId,participantRecordingId:s.participantRecordingId,participantUserId:s.participantUserId,participantRole:s.participantRole,sourceTranscriptSegmentId:s.id,globalSequence:s.globalSequence,participantSequence:s.participantSequence,startMs:s.startMs,endMs:s.endMs,normalizedText:s.normalizedText,normalizationFlags:s.flags,sourceProvider:s.provider,sourceModel:s.model,createdBy:actorUserId,updatedBy:actorUserId}))); });
  return timeline;
}
